plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/cayman@v0.2.0
include:
  - README.md
  - statemachine.md
  - howtofiles.md
  - plan.md
  - generated.md
  - Localization/localization.md
