plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/tactile@v0.2.0
include:
  - README.md
  - statemachine.md
  - howtofiles.md
  - plan.md

# Custom CSS overrides
sass:
  load_paths:
    - _sass
    - assets/css
